"""primera migracion

Revision ID: 21e4180257c4
Revises: 
Create Date: 2023-10-14 20:24:37.803403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e4180257c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicacion')
    op.drop_table('categoria')
    # ### end Alembic commands ###
